version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=henlo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    secrets:
      - pg_password

  web:
    image: henlo_web
    build: .
    command: daphne  -b 0.0.0.0 -p 8000 henlo.asgi:application
    volumes:
      - .:/code
    depends_on:
      - db
    secrets:
      - pg_password

  nginx:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_root:/static_root

  bot:
    image: henlo_web
    build: .
    command: python manage.py telegram_watcher
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - TELEGRAM_TOKEN_FILE=/run/secrets/telegram_token
    secrets:
      - telegram_token
      - pg_password

secrets:
  pg_password:
    external: true
  telegram_token:
    external: true
