# Generated by Django 3.0.2 on 2020-01-18 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('added', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
