# Generated by Django 3.0.2 on 2020-01-18 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('henlo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='id',
        ),
        migrations.AlterField(
            model_name='translation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
