# Generated by Django 3.0.2 on 2020-01-18 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flip_it_app', '0002_auto_20200118_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='translation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
