# Generated by Django 3.0.2 on 2020-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_it_app', '0003_auto_20200118_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='starred',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
